############################################
#####   Ericom Shield Vagrant (ova)    #####
###################################BH##CF###
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
#  config.vm.box = "boxcutter/ubuntu1604"
#  config.vm.box = "ubuntu/trusty64"
#  config.vm.box = "williamyeh/ubuntu-trusty64-docker"  -- was ubuntu 14
#  now moved to ubuntu 16.04  
    config.vm.box = "ubuntu/xenial64"
    config.disksize.size = '50GB'
#   config.vm.box = "v0rtex/xenial64"


#  Assign a friendly name to this host VM
   config.vm.hostname = "es-host"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
    config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 22, host: 10022
   config.vm.network "forwarded_port" , guest: 3128, host: 3128
   config.vm.network "forwarded_port" , guest: 8181, host: 8181
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  #  config.vm.network "public_network", bridge "enp1s0f0"


  # Share an additional folder to the guest VM. The first argument is

  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
   config.vm.synced_folder '.', '/vagrant', disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
 config.vm.provider "virtualbox" do |vb|
  vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  #   # Display the VirtualBox GUI when booting the machine
      # vb.gui = trued
      


      # set VM name
  vb.name = "shield-eval"
#      Doesnt work:
#      vb.product = "Ericom Shield"
#      vb.product-URL = "http://ericomshield.com/"
#      vb.Vendor = "Ericom Software"

     # Customize the amount of memory on the VM:
  vb.memory = "16192"
  vb.cpus = 4
 end

#
# View the documentation for the provider you are using for more
# information on available options.

# Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
# such as FTP and Heroku are also available. See the documentation at
# https://docs.vagrantup.com/v2/push/atlas.html for more information.
# config.push.define "atlas" do |push|
#   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
# end
  
# Enable provisioning with a shell script. Additional provisioners such as
# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
# documentation for more information about their specific syntax and use.
   
 config.vm.provision "shell", inline: <<-SHELL
#    echo ' ericomshield VM using Vagrant (18.07) '
     apt-get update
     apt-get upgrade
     apt-get install software-properties-common
     wget -q "https://raw.githubusercontent.com/EricomSoftwareLtd/Shield/Rel-18.07/Setup/show-my-ip.sh"
     chmod +x "./show-my-ip.sh" 
     echo "./show-my-ip.sh" >> .bashrc
     echo "========================>STARTING ERICOM SHIELD SCRIPT !!!!<==================================== "
     mkdir ericomshield
     cd ericomshield
     wget -q "https://raw.githubusercontent.com/EricomSoftwareLtd/Shield/Rel-18.07/Setup/ericomshield-setup.sh"
     chmod +x ericomshield-setup.sh
     ./ericomshield-setup.sh -quickeval -approve-eula -v Rel-18.07
     sudo  adduser --gecos "" ericom
     sudo  echo ericom:ericom | chpasswd
     sudo usermod -aG sudo ericom
     apt-get clean
     echo ' '
     echo ' '
     echo ' Your VM HostName is:'
     hostname
     echo ' Your VM address is:'
     echo ' '
     ../show-my-ip.sh
     echo ' '
     echo ' You can use these ports'
     echo ' port 3128 - Proxy'
     echo ' port 8181 - Admin'
     echo ' '
     echo ' Have a nice day'
  SHELL

end
