---
- name: Check if firewalld is installed
  package:
    name: firewalld
    state: present
  check_mode: true
  register: firewalld_check

- name: Make sure firewalld is disabled
  systemd:
    name: firewalld
    enabled: no
  when: not firewalld_check.changed

- name: Make sure firewalld is stopped
  systemd:
    name: firewalld
    state: stopped
  when: not firewalld_check.changed
