version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
proxy:
  remoteurl: https://registry-1.docker.io
  username: ericomshield1
  password: Ericom98765$
  delete:
    enabled: true
http:
  secret: vajajUlv0
  addr: 0.0.0.0:5000
