#!/bin/bash

APPDIR="$(dirname "$(readlink -f "${0}")")" #"

# Allow the AppImage to be symlinked to e.g., /usr/bin/commandname
# or called with ./Some*.AppImage commandname ...

if [ ! -z "$APPIMAGE" ]; then
    BINARY_NAME="$(basename "$ARGV0")"
else
    BINARY_NAME="$(basename "$0")"
fi
if [ ! -z "$1" ] && [ -e "$APPDIR/bin/$1" ]; then
    MAIN="$APPDIR/bin/$1"
    shift
elif [ ! -z "$1" ] && [ -e "$APPDIR/usr/bin/$1" ]; then
    MAIN="$APPDIR/usr/bin/$1"
    shift
elif [ -e "$APPDIR/bin/$BINARY_NAME" ]; then
    MAIN="$APPDIR/bin/$BINARY_NAME"
elif [ -e "$APPDIR/usr/bin/$BINARY_NAME" ]; then
    MAIN="$APPDIR/usr/bin/$BINARY_NAME"
else
    exec "$APPDIR/usr/bin/python3" "$APPDIR/usr/bin/ansible"
fi

exec "${MAIN}" "$@"
