#!/bin/sh

APPDIR="$(dirname "$(readlink -f "${0}")")" #"

export PATH="$APPDIR/bin:$APPDIR/usr/bin:$PATH"
export PYTHON="$APPDIR/usr/bin/python3"
export ANSIBLE_PLAYBOOK="$APPDIR/usr/bin/ansible-playbook"
export ANSIBLE_HOST_KEY_CHECKING="False"

# Allow the AppImage to be symlinked to e.g., /usr/bin/commandname
# or called with ./Some*.AppImage commandname ...

"$PYTHON" "$APPDIR/AppRun.py" "$@"
